### ISSUE TITLE
fluentd support

### ISSUE THREAD

**Issue by erdkse** [ZCube/bitnami-compat#1]
I would like to have fluentd images as well.

**Comment by erdkse** [comment]
thank you @ZCube it works - the only thing is that I receive `kubernetes_metadata` plugin is not found. But it should be - I couldn't understand if this is related to this repo or to bitnami itself. Any idea?

Thank you again for your great work!!

**Comment by ZCube** [comment]
> thank you @ZCube it works - the only thing is that I receive `kubernetes_metadata` plugin is not found. But it should be - I couldn't understand if this is related to this repo or to bitnami itself. Any idea?
> 
> Thank you again for your great work!!

@erdkse I did not notice that the plug-in was added inside. Added some plugins. After the build is finished, you will be able to use it. I haven't used this package myself yet, so it's untested.

**Comment by erdkse** [comment]
ahh thank you very much @ZCube - I was planning to add it by creating a PR - I will test it as soon as I can

**Comment by erdkse** [comment]
Works very well - thank you!!
