### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by jramoseguinoa** [ZCube/bitnami-compat#11]
Hi, I was wondering about building the image for MongoDB 4.4  but I'm not sure what to do on step "3. Write build scripts"
Bitnami uses official MongoDB images and I'm not sure if I have to write any build script.
Thanks

**Comment by ZCube** [comment]
@jramoseguinoa bitnami will fit the binaries they build themselves into their desired directory structure. In addition, certain plugin additions or setting changes may be applied.

**Comment by jramoseguinoa** [comment]
@ZCube thank you for the response. 
After running the script create.sh I'm getting a directory structure where I can see a docker file with some commented out lines


>#RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "yq" "4.20.2-0" --checksum cf127534dd75da82d58377bfd0d84f47fe1760830336a44365372805e48fe343
>#RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "wait-for-port" "1.0.1-9" --checksum 4b509978f6d0a4c3b958deeb3490241cda60e4412c138da665192631d60f70de
>#RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "render-template" "1.0.1-9" --checksum 4694f01476c5a457a71f280562df45ea542bdf3f9b298ff87643a89ea365f5fb
>#RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "mongodb" "4.4.12-5" --checksum 1a6f4d6ae38f229848ce5bf922a6248ba9dad000ee318bdc0fc7894b40d4e492
>#RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.14.0-6" --checksum 6f8fd2267481ffbe899a7f93b7b3076cd78dd70b7b9835bed79414932a749664


If I try to build the docker image, I got an error because there is an script that tries to use one of the dependencies listed there (render-template)

So back to my original question, I'm not sure what to do with the steps on the readme, specifically with 

> Check file list on archive/mariadb-10.6.5-3-linux-amd64-debian-10
>3. Write build scripts
>bash/mariadb/10.6.5-3/install.sh
>docker/mariadb/10.6.5-3/Dockerfile.from
>docker/mariadb/10.6.5-3/Dockerfile.install
>golang/mariadb/10.6.5-3/install.sh

The archive directory  contains some _tar.gz_ files that are the ones that are required, so my question is what should I do in order to include them in the image?

Sorry for the question but I'm new to this topic :D

**Comment by ZCube** [comment]
@jramoseguinoa after
```
./scripts/updates_with_checkout.sh 
```
Each component is replaced with a pre-written script. Since Bitnami does not prepare tar.gz, you have to write that part yourself.

Scripts for render-template and gosu are currently written in this repository, so you can check them by referring to the golang directory.

You need to write a Dockerfile for the mongodb installation, refer to mariadb's docker/mariadb/10.6.5-3/Dockerfile.install.

You need to place the file under the /opt/bitnami/mongodb directory and make it compatible with bitnami's scripts. Sometimes you may need to add plugins.

Unfortunately, this build system is not yet well-organized or documented.

**Comment by jramoseguinoa** [comment]
@ZCube today I was about to give it a try but I've seen that you already added the image. Thank you very much for adding this one.
I was able to install the v4.4 (v5 cannot be run in a rpi 4 as MongoDB 5.0 requires ARMv8.2-A or later) using the bitnami helm chart and the image you have created and everything seems to work (or at least the replicaset started as expected)

Once again thank you very much!
