### ISSUE TITLE
Bump kafka submodule to latest commit to support KRaft

### ISSUE THREAD

**Issue by arixmkii** [ZCube/bitnami-compat#17]
Bitnami with the help of community recently added changes to support KRaft (kafka w/o zookeeper). Would be nice to have this in bitnami-compat with arm64 builds.

**Comment by ZCube** [comment]
done

**Comment by arixmkii** [comment]
@ZCube  Thank you for this! But it seems that some more patching is necessary for the new images. I created #19 with updated description.
