### ISSUE TITLE
Encountered an Error when building: "failed to solve: rpc error: code = Unknown desc = docker.io/bitnami/minideb:bullseye: failed to do request"

### ISSUE THREAD

**Issue by makarov20211221** [ZCube/bitnami-compat#21]
thanks in advance sir

**Comment by makarov20211221** [comment]
Encountered an error
-----
root@localhost:~/bitnami-compat/bitnami-dockers/bitnami-docker-redis/7.0/debian-11# docker buildx build --platform linux/amd64,linux/arm64 -t mariadb:10.8 .
WARN[0000] invalid non-bool value for BUILDX_NO_DEFAULT_LOAD:  
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load 
[+] Building 10.0s (4/4) FINISHED                                                                                                                                                  
 => [internal] load .dockerignore                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                               0.0s
 => [internal] load build definition from Dockerfile                                                                                                                          0.0s
 => => transferring dockerfile: 1.39kB                                                                                                                                        0.0s
 => ERROR [linux/amd64 internal] load metadata for docker.io/bitnami/minideb:bullseye                                                                                        10.0s
 => ERROR [linux/arm64 internal] load metadata for docker.io/bitnami/minideb:bullseye                                                                                        10.0s
------
 > [linux/amd64 internal] load metadata for docker.io/bitnami/minideb:bullseye:
------
------
 > [linux/arm64 internal] load metadata for docker.io/bitnami/minideb:bullseye:
------
failed to solve: rpc error: code = Unknown desc = docker.io/bitnami/minideb:bullseye: failed to do request: Head "https://registry-1.docker.io/v2/bitnami/minideb/manifests/bullseye": dial tcp: lookup registry-1.docker.io on 100.100.144.2:53: read udp 172.17.0.2:56905->100.100.144.2:53: i/o timeout

**Comment by ZCube** [comment]
@makarov20211221 
It seems to be a dns problem. 100.100.144.2 It seems that you cannot connect to the dns server normally.

and 
```
docker buildx build --platform linux/amd64,linux/arm64 -t mariadb:10.8 . 
->
docker buildx build --platform linux/amd64,linux/arm64 -t mariadb:10.8 . -f Dockerfile.arm64
```

**Comment by makarov20211221** [comment]
Ok thanks, it Looks strange. In this step it seems requesting 
So I nslookup it and got
-----
nslookup registry-1.docker.io
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	registry-1.docker.io
Address: 44.207.51.64
Name:	registry-1.docker.io
Address: 44.194.5.25
Name:	registry-1.docker.io
Address: 44.207.96.114
--------
I guess my It team has some strange restriction there. I will confirm it tmr. Thank you for the reply sir !

**Comment by makarov20211221** [comment]
Could I ask if it's possible to change "registry-1.docker.io" to other sources ? My env is in Mainland China.... So "registry-1.docker.io" is not accessable....
Thank you.

**Comment by ZCube** [comment]
@makarov20211221
Looks like you'll have to find and use this kind of registry mirror.

* GCR mirror
https://cloud.google.com/container-registry/docs/pulling-cached-images?hl=ko

* ustc.edu.cn mirror (I don't use that mirror so I don't know if it's safe.)
https://mirrors.ustc.edu.cn/help/dockerhub.html
https://github.com/ustclug/mirrorhelp/blob/master/source/dockerhub.rst
