### ISSUE TITLE
Thanos support

### ISSUE THREAD

**Issue by anthr76** [ZCube/bitnami-compat#23]
Please considering adding support for thanos.

**Comment by ZCube** [comment]
@anthr76 For thanos I recommend using the official image

The task itself seems simple. It is a scratch image with only one '/bin/thanos' file.

When comparing the official image with the image of bitnami, there is no problem with compatibility.

And Docker images supports amd64, arm64, and ppc64le.

Currently, this repository cannot be a trusted source of truth, so I recommend using the official image.

Or is there any other reason you want to be managed in this repository?

from bitnami dockerfile(https://github.com/bitnami/bitnami-docker-thanos/blob/master/0/scratch/Dockerfile)
``` Dockerfile
...
FROM scratch

COPY prebuildfs /
COPY rootfs /
COPY --from=builder /opt/bitnami/thanos/bin/thanos /bin/thanos

USER 1001

ENTRYPOINT [ "/bin/thanos" ]
```

from thanos official repo(https://github.com/thanos-io/thanos/blob/main/Dockerfile)
```Dockerfile
# By default we pin to amd64 sha. Use make docker to automatically adjust for arm64 versions.
ARG BASE_DOCKER_SHA="14d68ca3d69fceaa6224250c83d81d935c053fb13594c811038c461194599973"
FROM quay.io/prometheus/busybox@sha256:${BASE_DOCKER_SHA}
LABEL maintainer="The Thanos Authors"

COPY /thanos_tmp_for_docker /bin/thanos

ENTRYPOINT [ "/bin/thanos" ]
```
