### ISSUE TITLE
Keycloak is different between bitnami and bitnami-compat

### ISSUE THREAD

**Issue by roderik** [ZCube/bitnami-compat#24]
I've been struggling a lot getting Keycloak configured to work correctly behind an nginx-ingress, and in the end found out that the environment variables the chart from bitnami set were not matching what the container needed.

I openend a ticket here https://github.com/bitnami/charts/issues/11358 but it seems that the Keycloak installed differs between this patched container and the original bitnami one.

**Comment by ZCube** [comment]
@roderik I'm trying to set it up to be compatible using the official binaries and docker. It is not possible to check every patch, but I remember that it worked in the initial patch work. What image is the image in which the issue occurred? It would be nice if you could give me the information needed to reproduce. Even if it's hard right now, I'll check it out when I have time.

**Comment by roderik** [comment]
yeah, no problem, let me explain what happens:

- launch the helm chart from bitnami, and set "proxy" to edge https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L207 (see https://github.com/bitnami/charts/issues/11358#issuecomment-1195605520 how to do just that)
- at the end of the line in the logs, proxied should be true

This happens because it sets this env var: https://github.com/bitnami/charts/blob/master/bitnami/keycloak/templates/configmap-env-vars.yaml#L18

Now, the env var used here is KEYCLOAK_PROXY
The official docs about this proxy var are found here https://www.keycloak.org/server/reverseproxy#_proxy_modes BUT, and this is where it goes wrong, it is not (or no longer?) KEYCLOAK_PROXY but is KC_PROXY (in the official code you download in the patch)

So, if you do the steps above, with the compat image, you will see the log to not be Proxied: true, but false.

You can work around it by setting this env var yourself by setting

```
  extraEnvVars:
    - name: KC_PROXY
      value: edge
```

In the container repo the var is handled here: https://github.com/bitnami/containers/blob/6b0581771bf13be39df66a372508d195b6367464/bitnami/keycloak/18/debian-11/rootfs/opt/bitnami/scripts/keycloak-env.sh#L120

They use libcomponent.sh to download keycloak, (I assume a custom version) but I have not figured out yet where it comes from

**Comment by roderik** [comment]
Oh, I've built in my own ghcr with a checkout of your repo, the image I use is here

```
  image:
    registry: ghcr.io
    repository: settlemint/bitnami-compat/keycloak
    tag: 18.0.2-debian-11-r17
```

It is public so you can use it, it is based on the commit just before you added keycloak config cli

**Comment by ZCube** [comment]
@roderik From my comparison, their image was almost identical to the keycloak official image. The difference was the addition of DB-related modules and keycloak-metrics-spi. 

It seems difficult to know which part is causing the difference at the moment.

**Comment by ZCube** [comment]
https://github.com/bitnami/containers/blob/44c2320bc81f6a437209353e97b8941ba2a0b4ab/bitnami/keycloak/18/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L95

https://github.com/bitnami/containers/blob/44c2320bc81f6a437209353e97b8941ba2a0b4ab/bitnami/keycloak/18/debian-11/rootfs/opt/bitnami/scripts/libkeycloak.sh#L217

/opt/bitnami/keycloak/conf/keycloak.conf

Referring to those lines, it seems that the config file is being created. It would be good to check the config file, printenv, and volume mount status of running containers.

**Comment by ZCube** [comment]
There was an issue with the execute permission of the bitnami script. I added a function to the Dockerfile generation tool that forcibly adds the execute permission to all sh because it seems that the execute permission is not set in Git or there is a problem in the build process.

```
keycloak@7db863adf5b8:/opt/bitnami/scripts$ ls -al
total 136
drwxr-xr-x 1 root root  4096 Jul 28 03:08 .
drwxr-xr-x 1 root root  4096 Jul 28 03:08 ..
drwxr-xr-x 2 root root  4096 Jul 28 03:08 java
drwxr-xr-x 2 root root  4096 Jul 28 03:08 keycloak
-rw-r--r-- 1 root root  5915 Jul 28 03:08 keycloak-env.sh
-rw-r--r-- 1 root root  1062 Jul 22 02:40 libbitnami.sh
-rw-r--r-- 1 root root  2054 Jul 22 02:40 libcomponent.sh
-rw-r--r-- 1 root root  4308 Jul 22 02:40 libfile.sh
-rw-r--r-- 1 root root  4481 Jul 22 02:40 libfs.sh
-rw-r--r-- 1 root root   580 Jul 22 02:40 libhook.sh
-rw-r--r-- 1 root root  9790 Jul 28 03:08 libkeycloak.sh
-rw-r--r-- 1 root root  2586 Jul 22 02:40 liblog.sh
-rw-r--r-- 1 root root  4536 Jul 22 02:40 libnet.sh
-rw-r--r-- 1 root root 11171 Jul 22 02:40 libos.sh
-rw-r--r-- 1 root root  4627 Jul 22 02:40 libpersistence.sh
-rw-r--r-- 1 root root  6600 Jul 22 02:40 libservice.sh
-rw-r--r-- 1 root root  5735 Jul 22 02:40 libvalidations.sh
-rw-r--r-- 1 root root  1365 Jul 22 02:40 libversion.sh
-rw-r--r-- 1 root root 14751 Jul 22 02:40 libwebserver.sh
```
