### ISSUE TITLE
Wordpress Support

### ISSUE THREAD

**Issue by joepa37** [ZCube/bitnami-compat#27]
Does [wordpress-nginx](https://github.com/ZCube/bitnami-compat/pkgs/container/bitnami-compat%2Fwordpress-nginx) equivalent to [bitnami/wordpress](https://hub.docker.com/r/bitnami/wordpress/)?

Thanks for amazing job!

**Comment by ZCube** [comment]
Not equivalent. I try to behave as similarly as possible, but settings may be different. The goal of this repository is to be able to use bitnami's charts as they are, with only image changes.

**Comment by ZCube** [comment]
use ghcr.io/zcube/bitnami-compat/wordpress:6.0.1-debian-11-r21

**Comment by joepa37** [comment]
I have tested this images, everything is working like a charm. Thanks a lot for this.
