### ISSUE TITLE
Odoo Support

### ISSUE THREAD

**Issue by joepa37** [ZCube/bitnami-compat#29]
Could you consider Odoo chart support? I have tried a custom image with arm support but some path doesn't match with the official bitnami chart values.

Thanks for amazing job btw.

**Comment by ZCube** [comment]
@joepa37 I looked at odoo, but found that it wasn't infrastructure related software. I don't think it's the software I'm using or interested in in the near future. It's hard to use the time for this. It is also mentioned in the README, but supporting all bitnami's charts is not currently the goal of this repository. Also, even if I write those images, few people will use them.

I recommend making a chart that uses the official image or modifying bitnami's chart to use the official image.
