### ISSUE TITLE
Request: add external-dns

### ISSUE THREAD

**Issue by iMartyn** [ZCube/bitnami-compat#30]
Unfortunately external-dns doesn't have official docker images, and it seems everyone using it is simply using it on amd64.

I appreciate that you're doing this because bitnami aren't and feel free to close with a "lol nope" kinda response, but it's one of the more annoying "just replace without bitnami" ones.

Cheers.

**Comment by ZCube** [comment]
@iMartyn

bitnami has many areas that I have no control over. (I have to check the build every week to make sure it works. This is a very annoying and time consuming task.)

I'm maintaining this project by myself, so it's a bit burdensome for this project to grow.

Therefore, recently, it has been added according to the following criteria.

1. Is there any alternative chart other than Bitnami Chart?

2. Is this a project I am interested in or will use?

3. Are there not many components included?

4. Does the official image not support the Bitnami chart?

5. Can someone test the built image for me? (I can't test well for images I don't know.)

6. Is the image so important that it cannot be replaced?

7. Do I have time? (I've been busy with work lately)

I'll add it to my TODO list for future.

Currently, the main reason for maintaining this repository is to make development and testing easier for some users (including me) who use mac m1 or rpi.

I thought that making this open source would be of interest to some, but it doesn't seem to have attracted much attention.

To be honest, I thought I could make a patch at the time I wrote this answer. My English is poor. :)

**Comment by iMartyn** [comment]
Your English is far better than any other language I speak (very beginner in anything else!)

I'm really grateful for your efforts, and I will happily test the image if you do make one at some point in the future.

I think Amazon and Oracle's push towards arm (especially oracle's generous always-free tier) is one fairly big reason you are seeing increased attention.

**Comment by ZCube** [comment]
@iMartyn 

I recommend using official image. registry.k8s.io/external-dns/external-dns:v0.12.2

Golang-based images are often compatible with official images.
