### ISSUE TITLE
Permission issue for Postgresql 14 using a strict security context

### ISSUE THREAD

**Issue by roderik** [ZCube/bitnami-compat#33]
I think the arm build is setting the permissions different here as well

<img width="1159" alt="CleanShot 2022-10-02 at 10 29 32@2x" src="https://user-images.githubusercontent.com/16780/193445250-d0e8f693-47ca-482e-92fe-22612c682473.png">

**Comment by ZCube** [comment]
Maybe it has been fixed.

**Comment by roderik** [comment]
@ZCube the latest 14.5 version is published a month ago? https://github.com/ZCube/bitnami-compat/pkgs/container/bitnami-compat%2Fpostgresql/versions?filters%5Bversion_type%5D=tagged

**Comment by ZCube** [comment]
@roderik There was a typo in the build script.

**Comment by roderik** [comment]
Works!
