### ISSUE TITLE
[FR] Discourse with arm compatibilty?

### ISSUE THREAD

**Issue by alf1e** [ZCube/bitnami-compat#36]
Is there a plan to add discourse with arm?

**Comment by ZCube** [comment]
@alf1e There are currently no plans to add Discourse.

**Comment by alf1e** [comment]
Aww. Is there any chance of getting it?

**Comment by ZCube** [comment]
The image consists of 8 components.

[{ruby 2.7.6-153} {wait-for-port 1.0.3-154} {brotli 1.0.9-153} {discourse 2.8.9-0} {gosu 1.14.0-154} {node 14.20.1-0} {postgresql-client 14.5.0-1} {python 3.8.14-1}]

❌  discourse:2.8.9
  ❌  python.3.8.14-1
  ❌  node.14.20.1-0
  ❌  brotli.1.0.9-153
  ❌  discourse.2.8.9-0

 4 of them are already prepared, and I will be able to patch up to 3 python, node, and brotli without problems.
 
 However, in the case of the last discourse, as a result of analyzing the files of the bitnami/discourse image, plug-ins or binaries are added. Therefore, the related work is likely to take time.
 
 And in the case of this image to me, I am not interested right now, so I have no plans.
  
 If you want to make a patch of the image, I can help up to 3 components: python, node, and brotli.

**Comment by alf1e** [comment]
So all I need to do is add Discourse?

**Comment by ZCube** [comment]
Maybe ….

**Comment by alf1e** [comment]
So all I have to do is install the binary? Sounds good.

**Comment by alf1e** [comment]
Oh. It's docker only... that makes this harder

**Comment by ZCube** [comment]
@alf1e  Check this..
The reason is unknown, but git is included, and the following difference was found through this. You will have to add all of those binaries.

```
docker run --rm -ti -w /opt/bitnami/discourse bitnami/discourse:2.8.9 git status

Refresh index: 100% (30952/30952), done.
Not currently on any branch.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Gemfile
        modified:   Gemfile.lock
        modified:   bin/bundle
        modified:   bin/rails
        modified:   bin/rake
        modified:   bin/unicorn
        modified:   public/images/transparent.png
        modified:   public/javascripts/pikaday/1.8.0/pikaday.js
        modified:   public/javascripts/squoosh/mozjpeg_enc.wasm

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .image_optim.yml
        bin/bootsnap
        bin/byebug
        bin/coderay
        bin/exifr
        bin/image_optim
        bin/mustache
        bin/nokogiri
        bin/oauth
        bin/objspace_recorder_convert.rb
        bin/passenger
        bin/passenger-config
        bin/passenger-install-apache2-module
        bin/passenger-install-nginx-module
        bin/passenger-memory-stats
        bin/passenger-status
        bin/pry
        bin/puma
        bin/pumactl
        bin/r2
        bin/racc
        bin/rackup
        bin/rbtrace
        bin/readability
        bin/rotp
        bin/rtlit
        bin/ruby-memory-profiler
        bin/sidekiq
        bin/sidekiqmon
        bin/sprockets
        bin/stackprof
        bin/stackprof-flamegraph.pl
        bin/stackprof-gprof2dot.py
        bin/thor
        bin/tilt
        bin/unicorn_rails
        licenses/
        passenger.3000.pid.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by alf1e** [comment]
Holy shit...

**Comment by ZCube** [comment]
The official discourse docker image also supports arm64, so why would you want a bitnami compatible docker image? Unless for a specific reason I recommend the official discourse docker image. If you build an image by writing a patch here, you won't get support.

https://github.com/discourse/discourse_docker/tree/main/image/base

**Comment by alf1e** [comment]
I'm trying to set it up through caprover and that uses the bitnami image

**Comment by ZCube** [comment]
I currently have no plans to add discourse myself. And I have guided you how to add those images that use this repository. So I'm going to close this issue. Good luck. 

I prefer to have no issues in the repositories. Because it's just a hobby,
