### ISSUE TITLE
can't pull image for mongodb 4.4.15

### ISSUE THREAD

**Issue by wesleyks** [ZCube/bitnami-compat#37]
Really appreciate the work you're doing here.

None of the mongodb v4 images are being successfully pulled, I keep getting a `manifest unknown` error.

```bash
# successful
> docker pull ghcr.io/zcube/bitnami-compat/mongodb:6.0.2 

# unsuccessful
> docker pull ghcr.io/zcube/bitnami-compat/mongodb:4.4.15
4.4.15: Pulling from zcube/bitnami-compat/mongodb
manifest unknown
```
Any idea on what's going on? Thanks

**Comment by ZCube** [comment]
Too many images were uploaded to ghcr, so I deleted untagged images 30 days ago between yesterday and today. However, it seems that the tool does not work properly and only the manifest is left.

The image has been restored. https://github.com/ZCube/bitnami-compat/actions/runs/3304137347

**Comment by wesleyks** [comment]
awesome, works now. thanks!
