### ISSUE TITLE
Support for MySQL

### ISSUE THREAD

**Issue by RedstoneWizard08** [ZCube/bitnami-compat#5]
Add the MySQL image (https://github.com/bitnami/bitnami-docker-mysql), this should be easy as we've done it before, I would do it but I forgot how to use your scripts. I would normally just clone it and modify it myself.

**Comment by ZCube** [comment]
@RedstoneWizard08 Do it in this order.

```
git add submodule ~~~url
./scripts/create.sh

... doing something ...

./scripts/updates_with_checkout.sh 
cd ~~~/*/debian-10
docker build . -t bitnami-test
docker run --rm -ti bitnami-test
```

**Comment by RedstoneWizard08** [comment]
I still have no idea how to apply the patches for gosu, ini-file, and others.

**Comment by ZCube** [comment]
> I still have no idea how to apply the patches for gosu, ini-file, and others.

It is located in ./scripts/updates_with_checkout.sh

**Comment by ZCube** [comment]
@RedstoneWizard08 Unlike other packages, mysql does not provide arm64 binaries for debian, so this request is not easy. It seems to have to be modified in the form of adding the bitnami script to the official docker image of centos-based mysql. The mysql package on debian uses mariadb.

https://www.mysql.com/support/supportedplatforms/database.html
