### ISSUE TITLE
Can't pull image for mongodb 5.0.6

### ISSUE THREAD

**Issue by ETtestim** [ZCube/bitnami-compat#55]
Great work maintaining this repo.

when trying to pull mongodb 5.0.6 I keep getting manifest unknown.

is this related to[https://github.com/ZCube/bitnami-compat/issues/37 ]()

image with tag 5.0.14 works perfectly.

thanks you.

**Comment by ddelange** [comment]
the earliest compat tag I can find is 5.0.10 https://hub.docker.com/r/zcube/bitnami-compat-mongodb/tags?page=1&ordering=-last_updated&name=5.0.

**Comment by ETtestim** [comment]
@ddelange Hi our team used this. 
https://github.com/zcube/bitnami-compat/pkgs/container/bitnami-compat%2Fmongodb/23142914?tag=5.0.6

**Comment by ETtestim** [comment]
it was working until recently

**Comment by ZCube** [comment]
I cleaned up old images from ghcr. It seems like an erased image at that time.

**Comment by ZCube** [comment]
The issue is that this repository is a free repository to keep too many and large images.

**Comment by ZCube** [comment]
You can build 5.0.6 by modifying the version of containers/bitnami/mongodb/5.0/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json.
```
git clone --recursive https://github.com/ZCube/bitnami-compat
cd bitnami-compat
...
# fix containers/bitnami/mongodb/5.0/debian-11/prebuildfs/opt/bitnami/.bitnami_components.json
# rm -rf containers/bitnami/mongodb/6.0
...
go run main.go generate --app=mongodb
go run main.go build --app=mongodb --tag {{your-docker-registry}}/bitnami-compat/ --push --platforms=linux/amd64,linux/arm64 
```

**Comment by ddelange** [comment]
@ZCube do you have to do that manually? I think untagged images might be garbage collected at some point

**Comment by ZCube** [comment]
@ETtestim I will not recover the 5.0.6 image because 5.0.14 is compatible with 5.0.6. Please let me know if you really need it.

**Comment by ETtestim** [comment]
Hi @ZCube thanks for your reply we will use 5.0.14.
