### ISSUE TITLE
Limit the versions that get generated, built and published

### ISSUE THREAD

**Issue by NikolayMetchev** [ZCube/bitnami-compat#56]
At the moment if you want to build just one app it still builds and push all versions of that app. It would be nice to be able to only build and push one version e.g. Postgresql 14 only.

**Comment by ddelange** [comment]
you could add a commit to your fork's `main` branch that commits out a part of the build matrix: https://github.com/ZCube/bitnami-compat/blob/69f950b413c0bf37992f0f11e3d1549378f5bd56/.github/workflows/build-on-push.yml#L23

and use https://probot.github.io/apps/pull/ to keep your fork's `main` branch synced with this repo

**Comment by NikolayMetchev** [comment]
Hi, Thanks for the suggestion. I can see how I can restrict this to just do postgres but I think it will still push 11,12,13,14 and 15.

**Comment by ZCube** [comment]
Building only a specific version range is currently not supported.

**Comment by ZCube** [comment]
@NikolayMetchev Fixed
```
go run main.go build --app=postgresql --version-prefix=14.
```

**Comment by NikolayMetchev** [comment]
Thank you very much
