### ISSUE TITLE
I can not download

### ISSUE THREAD

**Issue by nicefuture2016** [ZCube/bitnami-compat#65]
[root@test ~]# docker pull ghcr.io/zcube/bitnami-compat/mongodb:4.2.21-debian-10-r16
4.2.21-debian-10-r16: Pulling from zcube/bitnami-compat/mongodb
manifest unknown

I can not down the images,why?

**Comment by ddelange** [comment]
looks like a duplicate of https://github.com/ZCube/bitnami-compat/issues/55

i think the image you're trying to pull got untagged / garbage collected over time.

try one of the [existing tags](https://github.com/ZCube/bitnami-compat/pkgs/container/bitnami-compat%2Fmongodb/versions?filters%5Bversion_type%5D=tagged): for instance `docker pull ghcr.io/zcube/bitnami-compat/mongodb:4.2`

edit: that tag i mentioned ^ actually points to the same image as the [4.2.21-debian-10-r16](https://github.com/users/ZCube/packages/container/bitnami-compat%2Fmongodb/29117654?tag=4.2.21-debian-10-r16) tag: I'm also getting `manifest unknown`, also for the `4`, `5` and `6` tags 🤔

**Comment by nicefuture2016** [comment]
> looks like a duplicate of #55
> 
> i think the image you're trying to pull got untagged / garbage collected over time.
> 
> try one of the [existing tags](https://github.com/ZCube/bitnami-compat/pkgs/container/bitnami-compat%2Fmongodb/versions?filters%5Bversion_type%5D=tagged): for instance `docker pull ghcr.io/zcube/bitnami-compat/mongodb:4.2`
> 
> edit: that tag i mentioned ^ actually points to the same image as the [4.2.21-debian-10-r16](https://github.com/users/ZCube/packages/container/bitnami-compat%2Fmongodb/29117654?tag=4.2.21-debian-10-r16) tag: I'm also getting `manifest unknown`, also for the `4`, `5` and `6` tags 🤔

Hello, when I clone code from GitHub, I encountered a problem. Do you know what's going on? thanks

my command is ：git clone --recursive https://github.com/ZCube/bitnami-compat

`Cloning into 'C:/Users/HP/Desktop/bitnami-compat/charts/docs'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/bitnami/charts-docs/'
fatal: clone of 'https://github.com/bitnami/charts-docs' into submodule path 'C:/Users/HP/Desktop/bitnami-compat/charts/docs' failed
Failed to clone 'docs'. Retry scheduled
Cloning into 'C:/Users/HP/Desktop/bitnami-compat/charts/docs'...
`

**Comment by nicefuture2016** [comment]
seems https://github.com/bitnami/charts-docs/ is private now
