### ISSUE TITLE
postgresql images broken?

### ISSUE THREAD

**Issue by mreiger** [ZCube/bitnami-compat#9]
Hi, it seems the postgresql images are currently broken? My database pod (thankfully a test deployment) is crashlooping.
It worked before the recent image update.

Here's my pod; as you can see it was deployed from the bitnami helm chart:
```
kubectl --kubeconfig=/home/michael/.kube/k3s -n testcloud describe pod testcloud-postgresql-0 
Name:         testcloud-postgresql-0
Namespace:    testcloud
Priority:     0
Node:         server/10.0.1.147
Start Time:   Tue, 22 Feb 2022 18:35:30 +0100
Labels:       app.kubernetes.io/component=primary
              app.kubernetes.io/instance=testcloud
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=postgresql
              controller-revision-hash=testcloud-postgresql-cd8845ff9
              helm.sh/chart=postgresql-10.13.11
              role=primary
              statefulset.kubernetes.io/pod-name=testcloud-postgresql-0
Annotations:  <none>
Status:       Running
IP:           10.42.0.127
IPs:
  IP:           10.42.0.127
Controlled By:  StatefulSet/testcloud-postgresql
Containers:
  testcloud-postgresql:
    Container ID:   containerd://c07972b9496c7028b25ebd03b17cf04fb5bae999c792b87f4014406c9b695515
    Image:          ghcr.io/ghcr.io/zcube/bitnami-compat/postgresql:14-debian-10
    Image ID:       ghcr.io/ghcr.io/zcube/bitnami-compat/postgresql@sha256:9b110076bc68c6806e308001b7db618f4047b73b82047065dd0ca6ac15ac3097
    Port:           5432/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 22 Feb 2022 21:51:25 +0100
      Finished:     Tue, 22 Feb 2022 21:51:26 +0100
    Ready:          False
    Restart Count:  43
    Requests:
      cpu:      250m
      memory:   256Mi
    Liveness:   exec [/bin/sh -c exec pg_isready -U "nextcloud" -d "dbname=nextcloud" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/sh -c -e exec pg_isready -U "nextcloud" -d "dbname=nextcloud" -h 127.0.0.1 -p 5432
] delay=5s timeout=5s period=10s #success=1 #failure=6
    Environment:
      BITNAMI_DEBUG:                        false
      POSTGRESQL_PORT_NUMBER:               5432
      POSTGRESQL_VOLUME_DIR:                /bitnami/postgresql
      PGDATA:                               /bitnami/postgresql/data
      POSTGRES_POSTGRES_PASSWORD:           <set to the key 'postgresql-postgres-password' in secret 'testcloud-postgresql'>  Optional: false
      POSTGRES_USER:                        nextcloud
      POSTGRES_PASSWORD:                    <set to the key 'postgresql-password' in secret 'testcloud-postgresql'>  Optional: false
      POSTGRES_DB:                          nextcloud
      POSTGRESQL_ENABLE_LDAP:               no
      POSTGRESQL_ENABLE_TLS:                no
      POSTGRESQL_LOG_HOSTNAME:              false
      POSTGRESQL_LOG_CONNECTIONS:           false
      POSTGRESQL_LOG_DISCONNECTIONS:        false
      POSTGRESQL_PGAUDIT_LOG_CATALOG:       off
      POSTGRESQL_CLIENT_MIN_MESSAGES:       error
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES:  pgaudit
    Mounts:
      /bitnami/postgresql from data (rw)
      /dev/shm from dshm (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-testcloud-postgresql-0
    ReadOnly:   false
  dshm:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      Memory
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Normal   Pulled   11m (x42 over 3h16m)   kubelet  Container image "ghcr.io/ghcr.io/zcube/bitnami-compat/postgresql:14-debian-10" already present on machine
  Warning  BackOff  92s (x962 over 3h16m)  kubelet  Back-off restarting failed container
```

Here's the log from the container startup:

```
postgresql 20:51:25.94 
postgresql 20:51:25.94 Welcome to the Bitnami postgresql container
postgresql 20:51:25.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 20:51:25.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 20:51:25.96 
postgresql 20:51:25.98 INFO  ==> ** Starting PostgreSQL setup **
postgresql 20:51:26.00 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 20:51:26.01 INFO  ==> Loading custom pre-init scripts...
postgresql 20:51:26.02 INFO  ==> Initializing PostgreSQL database...
postgresql 20:51:26.06 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 20:51:26.06 INFO  ==> Generating local authentication configuration
postgresql 20:51:26.07 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 20:51:26.10 INFO  ==> Configuring replication parameters
/opt/bitnami/scripts/libpostgresql.sh: line 374: ((: 14
14: syntax error in expression (error token is "14")
postgresql 20:51:26.13 INFO  ==> Configuring fsync
postgresql 20:51:26.14 INFO  ==> Configuring synchronous_replication
postgresql 20:51:26.17 INFO  ==> Loading custom scripts...
postgresql 20:51:26.18 INFO  ==> Enabling remote connections
postgresql 20:51:26.20 INFO  ==> ** PostgreSQL setup finished! **

postgresql 20:51:26.22 INFO  ==> ** Starting PostgreSQL **
2022-02-22 20:51:26.277 GMT [1] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 800
2022-02-22 20:51:26.277 GMT [1] FATAL:  configuration file "/opt/bitnami/postgresql/conf/postgresql.conf" contains errors
```

The error message seems to lead to this function in the init script that tries to get the major version number: https://github.com/bitnami/bitnami-docker-postgresql/blob/42e404613f3e0c4120b0d4aea24d1d0fdae15eb3/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L1001

When I manually execute the statement in a test pod I get the version number, but twice. Could this be the problem; and if so is it specific to your build?

```
root@pgdebug:/# psql --version | grep -oE "[0-9]+\.[0-9]+" | grep -oE "^[0-9]+"
14
14
root@pgdebug:/# psql --version
psql (PostgreSQL) 14.2 (Debian 14.2-1.pgdg100+1)
```

Also, the version number in the pod is 14.2 but on the ghcr page it clams to be 14.1?

Since I can't attach the pod definition, here's the test pod yaml file:

```
apiVersion: v1
kind: Pod
metadata:
  name: pgdebug
  namespace: nextcloud
spec:
  containers:
  - image: ghcr.io/zcube/bitnami-compat/postgresql:14-debian-10
    imagePullPolicy: Always
    name: postgres
    env:
    - name: BITNAMI_DEBUG
      value: "true"
    command: 
    - sleep
    args:
    - "3600"
    securityContext:
      runAsUser: 0
```

**Comment by ZCube** [comment]
> Hi, it seems the postgresql images are currently broken? My database pod (thankfully a test deployment) is crashlooping. It worked before the recent image update.
> 
> Here's my pod; as you can see it was deployed from the bitnami helm chart:
> 
> ```
> kubectl --kubeconfig=/home/michael/.kube/k3s -n testcloud describe pod testcloud-postgresql-0 
> Name:         testcloud-postgresql-0
> Namespace:    testcloud
> Priority:     0
> Node:         server/10.0.1.147
> Start Time:   Tue, 22 Feb 2022 18:35:30 +0100
> Labels:       app.kubernetes.io/component=primary
>               app.kubernetes.io/instance=testcloud
>               app.kubernetes.io/managed-by=Helm
>               app.kubernetes.io/name=postgresql
>               controller-revision-hash=testcloud-postgresql-cd8845ff9
>               helm.sh/chart=postgresql-10.13.11
>               role=primary
>               statefulset.kubernetes.io/pod-name=testcloud-postgresql-0
> Annotations:  <none>
> Status:       Running
> IP:           10.42.0.127
> IPs:
>   IP:           10.42.0.127
> Controlled By:  StatefulSet/testcloud-postgresql
> Containers:
>   testcloud-postgresql:
>     Container ID:   containerd://c07972b9496c7028b25ebd03b17cf04fb5bae999c792b87f4014406c9b695515
>     Image:          ghcr.io/ghcr.io/zcube/bitnami-compat/postgresql:14-debian-10
>     Image ID:       ghcr.io/ghcr.io/zcube/bitnami-compat/postgresql@sha256:9b110076bc68c6806e308001b7db618f4047b73b82047065dd0ca6ac15ac3097
>     Port:           5432/TCP
>     Host Port:      0/TCP
>     State:          Waiting
>       Reason:       CrashLoopBackOff
>     Last State:     Terminated
>       Reason:       Error
>       Exit Code:    1
>       Started:      Tue, 22 Feb 2022 21:51:25 +0100
>       Finished:     Tue, 22 Feb 2022 21:51:26 +0100
>     Ready:          False
>     Restart Count:  43
>     Requests:
>       cpu:      250m
>       memory:   256Mi
>     Liveness:   exec [/bin/sh -c exec pg_isready -U "nextcloud" -d "dbname=nextcloud" -h 127.0.0.1 -p 5432] delay=30s timeout=5s period=10s #success=1 #failure=6
>     Readiness:  exec [/bin/sh -c -e exec pg_isready -U "nextcloud" -d "dbname=nextcloud" -h 127.0.0.1 -p 5432
> ] delay=5s timeout=5s period=10s #success=1 #failure=6
>     Environment:
>       BITNAMI_DEBUG:                        false
>       POSTGRESQL_PORT_NUMBER:               5432
>       POSTGRESQL_VOLUME_DIR:                /bitnami/postgresql
>       PGDATA:                               /bitnami/postgresql/data
>       POSTGRES_POSTGRES_PASSWORD:           <set to the key 'postgresql-postgres-password' in secret 'testcloud-postgresql'>  Optional: false
>       POSTGRES_USER:                        nextcloud
>       POSTGRES_PASSWORD:                    <set to the key 'postgresql-password' in secret 'testcloud-postgresql'>  Optional: false
>       POSTGRES_DB:                          nextcloud
>       POSTGRESQL_ENABLE_LDAP:               no
>       POSTGRESQL_ENABLE_TLS:                no
>       POSTGRESQL_LOG_HOSTNAME:              false
>       POSTGRESQL_LOG_CONNECTIONS:           false
>       POSTGRESQL_LOG_DISCONNECTIONS:        false
>       POSTGRESQL_PGAUDIT_LOG_CATALOG:       off
>       POSTGRESQL_CLIENT_MIN_MESSAGES:       error
>       POSTGRESQL_SHARED_PRELOAD_LIBRARIES:  pgaudit
>     Mounts:
>       /bitnami/postgresql from data (rw)
>       /dev/shm from dshm (rw)
> Conditions:
>   Type              Status
>   Initialized       True 
>   Ready             False 
>   ContainersReady   False 
>   PodScheduled      True 
> Volumes:
>   data:
>     Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
>     ClaimName:  data-testcloud-postgresql-0
>     ReadOnly:   false
>   dshm:
>     Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
>     Medium:      Memory
>     SizeLimit:   <unset>
> QoS Class:       Burstable
> Node-Selectors:  <none>
> Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
>                  node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
> Events:
>   Type     Reason   Age                    From     Message
>   ----     ------   ----                   ----     -------
>   Normal   Pulled   11m (x42 over 3h16m)   kubelet  Container image "ghcr.io/ghcr.io/zcube/bitnami-compat/postgresql:14-debian-10" already present on machine
>   Warning  BackOff  92s (x962 over 3h16m)  kubelet  Back-off restarting failed container
> ```
> 
> Here's the log from the container startup:
> 
> ```
> postgresql 20:51:25.94 
> postgresql 20:51:25.94 Welcome to the Bitnami postgresql container
> postgresql 20:51:25.95 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
> postgresql 20:51:25.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
> postgresql 20:51:25.96 
> postgresql 20:51:25.98 INFO  ==> ** Starting PostgreSQL setup **
> postgresql 20:51:26.00 INFO  ==> Validating settings in POSTGRESQL_* env vars..
> postgresql 20:51:26.01 INFO  ==> Loading custom pre-init scripts...
> postgresql 20:51:26.02 INFO  ==> Initializing PostgreSQL database...
> postgresql 20:51:26.06 INFO  ==> pg_hba.conf file not detected. Generating it...
> postgresql 20:51:26.06 INFO  ==> Generating local authentication configuration
> postgresql 20:51:26.07 INFO  ==> Deploying PostgreSQL with persisted data...
> postgresql 20:51:26.10 INFO  ==> Configuring replication parameters
> /opt/bitnami/scripts/libpostgresql.sh: line 374: ((: 14
> 14: syntax error in expression (error token is "14")
> postgresql 20:51:26.13 INFO  ==> Configuring fsync
> postgresql 20:51:26.14 INFO  ==> Configuring synchronous_replication
> postgresql 20:51:26.17 INFO  ==> Loading custom scripts...
> postgresql 20:51:26.18 INFO  ==> Enabling remote connections
> postgresql 20:51:26.20 INFO  ==> ** PostgreSQL setup finished! **
> 
> postgresql 20:51:26.22 INFO  ==> ** Starting PostgreSQL **
> 2022-02-22 20:51:26.277 GMT [1] LOG:  unrecognized configuration parameter "wal_keep_segments" in file "/opt/bitnami/postgresql/conf/postgresql.conf" line 800
> 2022-02-22 20:51:26.277 GMT [1] FATAL:  configuration file "/opt/bitnami/postgresql/conf/postgresql.conf" contains errors
> ```
> 
> The error message seems to lead to this function in the init script that tries to get the major version number: https://github.com/bitnami/bitnami-docker-postgresql/blob/42e404613f3e0c4120b0d4aea24d1d0fdae15eb3/14/debian-10/rootfs/opt/bitnami/scripts/libpostgresql.sh#L1001
> 
> When I manually execute the statement in a test pod I get the version number, but twice. Could this be the problem; and if so is it specific to your build?
> 
> ```
> root@pgdebug:/# psql --version | grep -oE "[0-9]+\.[0-9]+" | grep -oE "^[0-9]+"
> 14
> 14
> root@pgdebug:/# psql --version
> psql (PostgreSQL) 14.2 (Debian 14.2-1.pgdg100+1)
> ```
> 
> Also, the version number in the pod is 14.2 but on the ghcr page it clams to be 14.1?
> 
> Since I can't attach the pod definition, here's the test pod yaml file:
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: pgdebug
>   namespace: nextcloud
> spec:
>   containers:
>   - image: ghcr.io/zcube/bitnami-compat/postgresql:14-debian-10
>     imagePullPolicy: Always
>     name: postgres
>     env:
>     - name: BITNAMI_DEBUG
>       value: "true"
>     command: 
>     - sleep
>     args:
>     - "3600"
>     securityContext:
>       runAsUser: 0
> ```

@mreiger hot fixed. Execution was tested. The official binaries are gone, so you can't revert to a previous version. So 14.1 currently refers to 14.2. I'll take care of it later.

**Comment by mreiger** [comment]
Can confirm the fix. Thank you so much!
